### ISSUE TITLE
System.NullRefrenceException When using teleport

### ISSUE THREAD

**Issue by Avi-E-Koenig** [Windows10CE/DSPPlugins#1]
Version 1.1.0 of your plugin
Game Ver 0.6.16.5775

The plugin works and the TP aswell.
However there's an error message:

Please see screenshot of error.

![Screenshot 2021-02-12 201918](https://user-images.githubusercontent.com/12433441/107806537-aad7d100-6d6f-11eb-9b72-c0df5e354ec8.png)

P.s. awesome plugin !! <3

**Comment by Windows10CE** [comment]
Sorry for the late response, but I believe this issue should've been solved in a recent update with a reformat of how the different cheats work. Thanks for the report!
